#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Testing recipes
cookbook 'chef_handler'
cookbook 'minitest-handler',
  git: 'git://github.com/btm/minitest-handler-cookbook.git'
cookbook 'simple_cuke',
  git: 'git://github.com/iafonov/simple_cuke.git'

# Base
cookbook 'apt'
cookbook 'build-essential'
cookbook 'users'
cookbook 'sudo'
cookbook 'git'
cookbook 'openssl'
cookbook 'openssh'
cookbook 'cron'
cookbook 'xml'
cookbook 'zlib'
cookbook 'rsync'

# Tools / apps
cookbook 'zsh'
cookbook 'tmux'
cookbook 'vim'

# Databases
cookbook 'sqlite'

# Web server
cookbook 'nginx'
